import React from 'react';

const IndexPage = (props) => {
  return (
    <div className="scale">

    <h1>H1 title</h1>
    <h2>H2 title</h2>
    <h3>H3 title</h3>
    <h4>H4 title</h4>
    <h5>H5 title</h5>
    <h6>H6 title</h6>
    <p className="h7">H7 title</p>

    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>
   
    <h1>Font-scale(7)</h1>
    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>
   
    <h2>Font-scale(6)</h2>
    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>

    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>
  
    <h3>Font-scale(5)</h3>
    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>
    <h4>Font-scale(4)</h4>
    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>

    <h5>Font-scale(3)</h5>
    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>

    <h6>Font-scale(2)</h6>
    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>
  
    <p className="h7">Font-scale(1)</p>
    <p>Base font test <br /> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis sit amet diam at rhoncus. Praesent vel neque quis dui eleifend sollicitudin. Morbi id sollicitudin ligula. Vestibulum faucibus porta quam at euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non vehicula lectus, eu iaculis turpis. Suspendisse bibendum aliquet eros et volutpat. Ut et massa in quam volutpat semper quis sit amet metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nec tellus sagittis, lobortis urna sed, fermentum libero. Phasellus eleifend condimentum elit, eu ullamcorper tortor vestibulum id. Sed rhoncus vulputate nulla. Curabitur mauris velit, bibendum a elementum quis, gravida sed urna. Curabitur interdum rutrum augue non ultricies. Mauris semper vestibulum sem, in efficitur lorem ultrices vitae.</p>


<p className="small">Font-scale(-1) <br />
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam iaculis auctor ligula, sed lobortis ipsum eleifend vitae. Phasellus gravida condimentum purus, vitae posuere magna aliquet sed. Nullam velit orci, suscipit id felis eu, egestas aliquet urna. Phasellus tincidunt nulla gravida sapien venenatis, vel sollicitudin arcu elementum. Sed blandit sollicitudin risus, non euismod magna dictum ut. Integer pharetra dui metus, at tempor elit elementum ut. Etiam vitae tortor ac nulla mollis molestie.</p>
<p className="verySmall">Font-scale(-2)<br />Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam iaculis auctor ligula, sed lobortis ipsum eleifend vitae. Phasellus gravida condimentum purus, vitae posuere magna aliquet sed. Nullam velit orci, suscipit id felis eu, egestas aliquet urna. Phasellus tincidunt nulla gravida sapien venenatis, vel sollicitudin arcu elementum. Sed blandit sollicitudin risus, non euismod magna dictum ut. Integer pharetra dui metus, at tempor elit elementum ut. Etiam vitae tortor ac nulla mollis molestie.</p>

    </div>
  )

}

export default IndexPage;
